[package]
name = "discord_apple_music_rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
discord-rich-presence = "0.2.1"
sysinfo = "0.24.6"
osascript = "0.3.0"
serde = { version = "1.0.139", features = ["derive"] }
percent-encoding = "2.1.0"
reqwest = { version = "0.11.11", features = ["json"] }
serde_json = "1.0.82"
tokio = { version = "1.20.0", features = ["full"] }
